SharePoint "Full kontroll" tilgangsnivå rettighetssjekk
Puzzlepart/prosjektportalen365 pull request #1055
Opened 2023-03-23 16:34 UTC by Remi749

# Pull request (PR)

Sørg for at du ber om PR for din branch (høyre side). Sørg for at du gjør en PR mot dev-branchen (venstre side). Sjekk commits og alle commit-meldingene.

## Sjekklisten din

Alle sjekkpunktene under må være sjekket av og godkjent for at vi skal kunne merge branchen din mot dev.

- [X] Sjekk at din branch ikke feiler på `linting`.
- [X] Legg ved beskrivelse i [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md), markert med **ID av issue** knyttet til PR-en
- [X] Angi korrekt `Milestone` på PR-en og issuet
- [X] Tilegn deg selv PR-en og legg til `labels`

### Beskrivelse

Dersom bruker har "Full kontroll" tilgangsnivå på området får bruker fulle rettigheter på området.

Colin har fått tilgangsnivået "Full kontroll" via en SharePoint gruppe. Før så betydde dette at brukeren ikke hadde noen rettigheter til å redigere prosjektinformasjon osv... Dette er nå endret. Brukeren får nå fulle rettigheter på området.

| Før      | Etter      |
| -------- | ---------- |
| ![image](https://user-images.githubusercontent.com/28678468/227271733-7ae33896-c349-447d-acaa-935aa04d81d9.png) | ![image](https://user-images.githubusercontent.com/28678468/227271773-194eb859-bb19-4c8f-9c48-d964103bac64.png) |

### Hvordan teste

Vennligst beskriv hvordan noen andre (en vanlig bruker uten kodeferdigheter) kan teste denne PR-en. Følg eksempelet under, punktene du legger ved vil bli brukt når vi tester neste versjon av Prosjektportalen

| #   | Handling          | Forventet resultat     |
| --- | ----------------- | ---------------------- |
| 1   | Sett tilgangsnivå "Full kontroll" på en bruker  | Se at brukeren får fulle rettigheter på området  |

### Relevante issues (hvis aktuelt)

- #1054

2023-03-23 19:24 UTC, tarjeieo submitted a review, later dismissed
💪

2023-03-24 07:57 UTC, olemp requested changes

2023-03-24 07:57 UTC, olemp commented on SharePointFramework/@Shared/src/data/SPDataAdapterBase/index.ts
> +                  const currentUserHasManageWebPermisson = await sp.web.currentUserHasPermissions(PermissionKind.ManageWeb)
@Remi749 Endret til å bruke `sp.web.currentUserHasPermissions(PermissionKind.ManageWeb)` [her](https://github.com/Puzzlepart/prosjektportalen365/pull/1055/commits/ce389eff501415aadeb7b469ba962d8bb01e9ac4), men det var kanskje en grunn til at du ikke brukte denne?

2023-03-24 08:09 UTC, olemp commented on SharePointFramework/@Shared/src/data/SPDataAdapterBase/index.ts
>            if (!_.isArray(rolesToCheck) || _.isEmpty(rolesToCheck)) {
Men det gir jo ikke mening? Vi skal nå erstatte spadmin-checken med manageweb-checken. Om det er satt roller og spadmin-rollen ikke er med, skal det ikke returneres true. D

2023-03-24 08:13 UTC, olemp commented on SharePointFramework/@Shared/src/data/SPDataAdapterBase/index.ts
>            if (!_.isArray(rolesToCheck) || _.isEmpty(rolesToCheck)) {
Om kunden velger ingen roller => manageweb-tilgangen er tilstrekkelig
Om kunden velger roller, deriblant spadmin-roller som sjekker manageweb-tilgag => manageweb-tilgangen er tilstrekkelig
Om kunden velger roller, men ikke spadmin-rollen, bør vi ikke returnere `true`. Da vil vi ikke dekke caser hvor man vi skille tilgang til prosjektområdet og tilgang til prosjektegenskaper.

FYI @Remi749 @tarjeieo

2023-03-24 08:28 UTC, Remi749 commented on SharePointFramework/@Shared/src/data/SPDataAdapterBase/index.ts
>            if (!_.isArray(rolesToCheck) || _.isEmpty(rolesToCheck)) {
Okei, det kan hende jeg har misforstått eller at det jeg skrev ikke var tydelig nok. For jeg trodde etter kodeendringen din at følgende ikke gjaldt lengre:

"Om kunden velger ingen roller => manageweb-tilgangen er tilstrekkelig"

Men da er vi good, carry on <3

2023-03-24 09:08 UTC, merged