Fiks for Gevinstoversikt på prosjektnivå
Puzzlepart/prosjektportalen365 pull request #1096
Opened 2023-04-26 10:47 UTC by olemp

# Pull request (PR)

Sørg for at du ber om PR for din branch (høyre side). Sørg for at du gjør en PR mot riktig release-branch (venstre side). Sjekk commits og alle commit-meldingene.

## Sjekklisten din

Alle sjekkpunktene under må være sjekket av og godkjent for at vi skal kunne merge branchen din mot dev.

- [ ] Sjekk at din branch ikke feiler på `linting`.
- [ ] Legg ved beskrivelse i [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md), markert med **ID av issue** knyttet til PR-en
- [x] Angi korrekt `Milestone` på PR-en og issuet, samt tilegn deg selv PR-en og legg til `labels`

### Beskrivelse

Fiks for Gevinstoversikt på prosjektnivå.

### Relevante issues (hvis aktuelt)
#1095

## Sjekkliste for godkjenner

Alle sjekkpunktene under må være sjekket av og godkjent av reviewers for at vi skal kunne merge branchen din mot dev.

- [ ] Sjekk at det er fylt ut testpunkter
- [ ] Sjekk om det er nødvendig å nevne denne PR i release notes
- [ ] Sjekk om det er nødvendig å oppdatere dokumentasjon for hjelpeinnhold
  - Ta en titt på [Brukermanual for Prosjektportalen 365](https://puzzlepart.github.io/prosjektportalen-manual/) og vurder behovet for oppdateringer.

2023-04-26 12:33 UTC, Remi749 commented on Install/Scripts/EnsureProjectAggregrationWebPart/JsonControlData_Gevinstoversikt.json
>      "columns": [
Wups, ja det burde det :P

2023-04-26 12:35 UTC, olemp commented on Install/Scripts/EnsureProjectAggregrationWebPart/JsonControlData_Gevinstoversikt.json
>      "columns": [
Mulig vi kan fikse det for akkurat denne nå i denne PRen. Skal teste i https://puzzlepart.sharepoint.com/sites/pp365/.

2023-04-26 12:41 UTC, olemp commented on Install/Scripts/EnsureProjectAggregrationWebPart/JsonControlData_Gevinstoversikt.json
>      "columns": [
@Remi749 Skal vi kjøre fiksen i denne PRen foreløpig, og evt rydde opp i 1.9? Eller skal vi gjøre en større fiks til 1.8.2?

cc @tarjeieo

2023-04-26 12:53 UTC, tarjeieo commented on Install/Scripts/EnsureProjectAggregrationWebPart/JsonControlData_Gevinstoversikt.json
>      "columns": [
Jeg synes vi skal kjøre enkel fiks i 1.8.2 og laget et nytt issue for dette som kan være kandidat for 1.9

2023-04-26 12:53 UTC, Remi749 commented on Install/Scripts/EnsureProjectAggregrationWebPart/JsonControlData_Gevinstoversikt.json
>      "columns": [
Enig

2023-04-26 12:56 UTC, olemp commented on Install/Scripts/EnsureProjectAggregrationWebPart/JsonControlData_Gevinstoversikt.json
>      "columns": [
@Remi749 @tarjeieo Enig med dere, opprettet https://github.com/Puzzlepart/prosjektportalen365/issues/1097

2023-04-27 07:09 UTC, Remi749 requested changes
Good stuff, noen testpunkter i PR så er vi der.

2023-04-27 07:14 UTC, olemp commented
> Good stuff, noen testpunkter i PR så er vi der.

Done

2023-04-27 07:15 UTC, Remi749 approved these changes

2023-04-27 07:15 UTC, merged