Unngå begrensninger på planneroppgaver + logging
Puzzlepart/prosjektportalen365 pull request #1101
Opened 2023-05-02 09:39 UTC by Remi749

# Pull request (PR)

Sørg for at du ber om PR for din branch (høyre side). Sørg for at du gjør en PR mot riktig release-branch (venstre side). Sjekk commits og alle commit-meldingene.

## Sjekklisten din

Alle sjekkpunktene under må være sjekket av og godkjent for at vi skal kunne merge branchen din mot dev.

- [X] Sjekk at din branch ikke feiler på `linting`.
- [X] Legg ved beskrivelse i [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md), markert med **ID av issue** knyttet til PR-en
- [X] Angi korrekt `Milestone` på PR-en og issuet, samt tilegn deg selv PR-en og legg til `labels`

### Beskrivelse

Problemer hvor ingen elementer kom med under provisjonering dersom noen begrensninger var nådd er fikset. Dette gjelder følgende:

- Sjekkliste elementer per oppgave: 20 elementer
  - Logges i loggliste
- Beskrivelse på sjekkliste: 100 karakterer
- Vedlegg per oppgave: 10 elementer
  -   Logges i loggliste
- Etiketter på planner: 25 elementer
-   Logges i loggliste

![image](https://user-images.githubusercontent.com/28678468/235631055-4e1a040c-b18a-4e99-8546-3ac1d262c2a9.png)

### Hvordan teste

Vennligst beskriv hvordan noen andre (en vanlig bruker uten kodeferdigheter) kan teste denne PR-en. Følg eksempelet under, punktene du legger ved vil bli brukt når vi tester neste versjon av Prosjektportalen

|  #   | Handling          | Forventet resultat     |
| -- | -- | --|
| 1 | Angi verdier som overskyter alle begrensninger | Det er angitt verdier i Planner oppgavelisten som skal testes|
| 2 | Logging - Sjekkliste elementer per oppgave: 20 elementer | Sjekk at det logges i loggliste |
| 3 | Logging - Vedlegg per oppgave: 10 elementer | Sjekk at det logges i loggliste |
| 4 | Logging - Etiketter på planner: 25 elementer | Sjekk at det logges i loggliste |
| 5 | Sjekk at beskrivelse på sjekkliste blir begrenset (100 karakterer) og at innholdet følger med | Innhold som er under 100 karakterer skal bli satt. |
| 6 | Sjekk at vedlegg på oppgaven blir begrenset (10 elementer) og at innholdet følger med | Vedlegg skal bli satt (kun for de som er under 10 vedlegg). |
| 7 | Sjekk at sjekkliste elementer på oppgaven blir begrenset (20 elementer) og at innholdet følger med | Sjekkpunkter skal bli satt (kun for de som er under 20 elementer). |
| 8 | Sjekk at etiketter for planneren blir begrenset (25 etiketter) | Etiketter skal bli satt (kun for de som er under 25). |

### Relevante issues (hvis aktuelt)

- #1039 

## Sjekkliste for godkjenner

Alle sjekkpunktene under må være sjekket av og godkjent av reviewers for at vi skal kunne merge branchen din mot dev.

- [ ] Sjekk at det er fylt ut testpunkter
- [ ] Sjekk om det er nødvendig å nevne denne PR i release notes
- [ ] Sjekk om det er nødvendig å oppdatere dokumentasjon for hjelpeinnhold
  - Ta en titt på [Brukermanual for Prosjektportalen 365](https://puzzlepart.github.io/prosjektportalen-manual/) og vurder behovet for oppdateringer.

2023-05-02 11:12 UTC, olemp commented on SharePointFramework/ProjectExtensions/package.json
> -    "serve": "concurrently \"gulp serve-deprecated --locale=nb-no --nobrowser\"",
Denne skal være --nobrowser som default.

2023-05-02 11:14 UTC, Remi749 commented on SharePointFramework/ProjectExtensions/package.json
> -    "serve": "concurrently \"gulp serve-deprecated --locale=nb-no --nobrowser\"",
Oisann good catch! den har kommet med som en feil. Will fix

2023-05-02 11:15 UTC, olemp requested changes
![image](https://user-images.githubusercontent.com/7606007/235651453-09c490ac-47f5-4bdd-a15e-dc91c1a98f8e.png)

2023-05-02 11:17 UTC, olemp approved these changes
Smooth sailing <3

2023-05-02 11:27 UTC, merged

2023-05-25 22:51 UTC, pzljanb commented
Hvor er Logglisten å finne @Remi749 ?

2023-05-30 07:18 UTC, Remi749 commented
> 

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/ea5dd2fe-0aec-43d2-b2ee-fb0c1a0494db)