Added project status PNG snapshot on project status report publish
Puzzlepart/prosjektportalen365 pull request #337
Opened 2020-11-13 08:35 UTC by Petterandre

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check your code additions will fail linting checks
- [x] Remember: Add PR description to [Changelog](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

When publishing a status report, adds a snapshot available on the project status page.
The file is attached to the list element.

PDF is not included, as it proves much more challenging. Will be on the back burner

### How to test

1. Create a new status report
2. Publish
3. View snapshot

Closes #324 

💔Thank you!

2020-11-18 13:59 UTC, olemp requested changes
... also, how is errors handled? If there's an error attaching  the PNG for instance? Is it graceful?

Also, resolve conflicts and run `npm run lint`.

(I hate this feature so much)

2020-11-18 13:59 UTC, olemp commented on SharePointFramework/@Shared/src/services/PortalDataService/index.ts
>          await this._web.lists.getByTitle(this._configuration.listNames.PROJECT_STATUS).items.getById(id).update(properties);
Initialize a variable with the list first? More readable.

2020-11-18 13:59 UTC, olemp commented on SharePointFramework/ProjectWebParts/src/components/ProjectStatus/index.tsx
> +      name: "Åpne som øyeblikksbilde",
Add resources to `strings`

2020-11-20 08:20 UTC, Petterandre commented
> ... also, how is errors handled? If there's an error attaching the PNG for instance? Is it graceful?
> 
> Also, resolve conflicts and run `npm run lint`.
> 
> (I hate this feature so much)

Errors now handled. lint script does not exist in @Shared, but should pass, looking at the existing code.

I'm sorry, I know you hate it, dear.

2020-11-20 08:49 UTC, Petterandre commented
There are a few more fixes incoming.

2020-11-20 08:50 UTC, olemp commented
> There are a few more fixes incoming.

Use draft mode then 🚀

2020-11-20 10:44 UTC, olemp commented
Run `lint` please 👨‍🎤 🎸

2020-11-20 16:31 UTC, Petterandre commented
Ran lint once more, there was an unlinted file. Had to remove prettier temporarily, as it failed for some unknown reason.

2020-11-20 19:49 UTC, merged

2020-11-26 12:07 UTC, pzljanb commented
Works well