Converting SP dates to readable excel date format
Puzzlepart/prosjektportalen365 pull request #495
Opened 2021-08-01 11:51 UTC by Rundez

### Your checklist for this pull request

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [X] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [X] Check the commit's or even all commits' message 
- [X] Check if your code additions will fail linting checks
- [X] Remember: Add PR description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

When exporting project information with dates from "Porteføljeoversikt", the dates were not recognized by excel due to the format. 
The solution: Convert the Sharepoint date format to a standard JS date object recognized by excel. 

### How to test

1. Navigate to "Porteføljeoversikt", add start and end date columns, then export to excel. 
2. The dates should now be recognized by excel. 

### Relevant issues (if applicable)
fixes #487 

💔Thank you!

2021-08-01 17:47 UTC, olemp requested changes
Too hardcoded in my opinion. Only works for these two date fields. We should look into a more dynamic solution that works for all date fields, including custom ones.

2021-08-02 08:55 UTC, tarjeieo commented
> Too hardcoded in my opinion. Only works for these two date fields. We should look into a more dynamic solution that works for all date fields, including custom ones.

I agree that it's not ideal. How about iterating over properties of the item, converting those ending with *OWSDATE to proper date values?

2021-08-02 08:57 UTC, olemp commented
> > Too hardcoded in my opinion. Only works for these two date fields. We should look into a more dynamic solution that works for all date fields, including custom ones.
> 
> I agree that it's not ideal. How about iterating over properties of the item, converting those ending with *OWSDATE to proper date values?

We should have access to the columns array, where we have the column config and can catch if it's a date.

2021-08-04 06:36 UTC, Rundez commented
I agree. Added a solution that iterates the columns and checks the field type. This should also convert any custom date values.

2021-08-17 09:15 UTC, tarjeieo commented
Any input here @olemp ? Can this be merged?

2021-08-17 09:38 UTC, olemp commented
> Any input here @olemp ? Can this be merged?

Still want to have a look through it. Should have time this week - tomorrow or Thu.

2021-08-24 13:41 UTC, tarjeieo commented
> > Any input here @olemp ? Can this be merged?
> 
> Still want to have a look through it. Should have time this week - tomorrow or Thu.

Friendly reminder :)

2021-08-25 07:48 UTC, olemp requested changes
Se comments.

2021-08-25 07:48 UTC, olemp commented on SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverviewCommands/index.tsx
> +      fltColumns.map((col) => {
@Rundez You're using `Array.map` without returning anything. Seems like it's `Array.forEach` you want to use here.

2021-08-25 07:50 UTC, olemp commented
See [Array.map documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

2021-08-30 06:49 UTC, merged

2021-09-03 11:13 UTC, danielwiese commented
Tested OK