Added Phase parameter to new template
Puzzlepart/prosjektportalen365 pull request #637
Opened 2022-02-02 14:59 UTC by Petterandre

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check if your code additions will fail linting checks
- [x] Remember: Add issue description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the **ID of the Issue** associated with this PR
- [x] Documentation: Have a look at the [PP365 User manual](https://puzzlepart.github.io/prosjektportalen-manual/) and consider the need for updates to be made. Updates can be done directly into the 'Kladd' branch or by providing information to test team for implementation.

### Description

PR is part of the template rework, bugfixes and minor changes, 
Note: It is part of unreleased functionality, so it won't be a part of the changelog

### How to test

- [] 1. Set a value to Term set Ids different than the default value.
- [] 2. Create a project with the template
- [] 3. See that it works

### Relevant issues (if applicable)
Closes #630 

💔Thank you!

2022-02-02 18:15 UTC, tarjeieo requested changes

2022-02-02 18:15 UTC, tarjeieo commented on SharePointFramework/ProjectExtensions/src/projectSetup/index.ts
> +      const files = await this._portal.getItems('Prosjektmaler', ProjectTemplateFile, {}, ['File'])
Finnes denne også som en property/parameter vi kan bruke fra et sted? Istedenfor å hardkode inn?

2022-02-02 18:24 UTC, Petterandre commented on SharePointFramework/ProjectExtensions/src/projectSetup/index.ts
> +      const files = await this._portal.getItems('Prosjektmaler', ProjectTemplateFile, {}, ['File'])
Kan bruke strings, som vi har gjort med andre lister?

2022-02-02 18:26 UTC, tarjeieo commented on SharePointFramework/ProjectExtensions/src/projectSetup/index.ts
> +      const files = await this._portal.getItems('Prosjektmaler', ProjectTemplateFile, {}, ['File'])
Jepp, referer bare mot stringen Lists_ProjectTemplates_Title som allerede finnes

2022-02-03 07:38 UTC, Petterandre commented on SharePointFramework/ProjectExtensions/src/projectSetup/index.ts
> +      const files = await this._portal.getItems('Prosjektmaler', ProjectTemplateFile, {}, ['File'])
Måtte opprette ny streng, List_ProjectTemplates_Title var i resx, opprettet tilsvarende streng i extensions

2022-02-03 08:20 UTC, tarjeieo approved these changes

2022-02-03 08:28 UTC, merged